#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS_DIR = ROOT / "requirements"
LOCKFILES = ["bootstrap.txt", "build.txt", "runtime.txt", "docker.txt", "dev.txt"]
COMPATIBILITY_LOCKFILES = {
    "bootstrap.lock": "bootstrap.txt",
    "build.lock": "build.txt",
    "runtime.lock": "runtime.txt",
    "docker.lock": "docker.txt",
    "dev.lock": "dev.txt",
}
HASH_RE = re.compile(r"--hash=sha256:[0-9a-f]{64}")
WINDOWS_ABSOLUTE_PATH_RE = re.compile(r"[A-Za-z]:\\")


def main() -> int:
    ok = True
    for name in LOCKFILES:
        path = REQUIREMENTS_DIR / name
        display_path = path.relative_to(ROOT).as_posix()
        if not path.exists():
            print(f"MISSING {display_path}: generate it with python scripts/compile_lockfiles.py")
            ok = False
            continue
        text = path.read_text(encoding="utf-8")
        if "autogenerated by pip-compile with Python 3.12" not in text:
            print(f"INVALID {display_path}: header does not indicate Python 3.12 generation")
            ok = False
        if WINDOWS_ABSOLUTE_PATH_RE.search(text) or str(ROOT) in text or ROOT.as_posix() in text:
            print(f"INVALID {display_path}: contains a local absolute path")
            ok = False
        if "--generate-hashes" not in text and not HASH_RE.search(text):
            print(f"INVALID {display_path}: no sha256 hashes found")
            ok = False
        for line in text.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith(("#", "--", "    --hash", "-", " ")) and "==" not in stripped:
                print(f"SUSPICIOUS {display_path}: unpinned requirement line: {stripped}")
                ok = False
    for wrapper_name, target_name in COMPATIBILITY_LOCKFILES.items():
        wrapper = REQUIREMENTS_DIR / wrapper_name
        expected = f"-r {target_name}\n"
        if not wrapper.exists():
            print(f"MISSING {wrapper.relative_to(ROOT).as_posix()}: generate it with python scripts/compile_lockfiles.py")
            ok = False
        elif wrapper.read_text(encoding="utf-8") != expected:
            print(f"INVALID {wrapper.relative_to(ROOT).as_posix()}: expected compatibility include for {target_name}")
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
